.TH "QE_roots" 3 "Fri Aug 26 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QE_roots
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <quadratic_equation\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcount_roots\fP"
.br
.ti -1c
.RI "double \fBx1\fP"
.br
.ti -1c
.RI "double \fBx2\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int QE_roots::count_roots"

.SS "double QE_roots::x1"

.SS "double QE_roots::x2"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
