.TH "/mnt/c/Users/actim/code/c/square/quadratic_equation.cpp" 3 "Fri Aug 26 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Users/actim/code/c/square/quadratic_equation.cpp \- quadratic equation code file  

.SH SYNOPSIS
.br
.PP
\fC#include 'quadratic_equation\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBcheck_flag_test\fP (int argc, char *argv[])"
.br
.ti -1c
.RI "void \fBfix_zero_double\fP (double *a)"
.br
.ti -1c
.RI "void \fBarrange_double\fP (double *a, double *b)"
.br
.ti -1c
.RI "void \fBstart_solve\fP ()"
.br
.RI "This function calls the user interface in the console\&. "
.ti -1c
.RI "void \fBswap_double\fP (double *a, double *b)"
.br
.RI "A function that swaps two numbers of the double type\&. "
.ti -1c
.RI "void \fBclear_buffer\fP ()"
.br
.RI "Function for clearing the input buffer\&. "
.ti -1c
.RI "bool \fBequal_double\fP (double a, double b)"
.br
.RI "Function for comparing 2 numbers of type double\&. "
.ti -1c
.RI "void \fBlinear_equation\fP (const \fBQE_coeff\fP coeff, \fBQE_roots\fP *roots)"
.br
.RI "The function of solving a linear equation\&. "
.ti -1c
.RI "void \fBquadratic_equation\fP (const \fBQE_coeff\fP coeff, \fBQE_roots\fP *roots)"
.br
.RI "The function of solving the correct quadratic equation\&. "
.ti -1c
.RI "void \fBsolveqe\fP (const \fBQE_coeff\fP coeff, \fBQE_roots\fP *roots)"
.br
.RI "The function of solving the quadratic equation\&. "
.in -1c
.SH "Detailed Description"
.PP 
quadratic equation code file 


.SH "Function Documentation"
.PP 
.SS "void arrange_double (double * a, double * b)"

.SS "bool check_flag_test (int argc, char * argv[])"

.PP
\fBParameters\fP
.RS 4
\fIargc\fP number of command line arguments 
.br
\fIargv\fP array of command line arguments
.RE
.PP
Если один из флагов командной строки -d , то true, иначе false
.PP
\fBReturns\fP
.RS 4
If one of the command line flags is -d , then true otherwise fals\&. 
.RE
.PP

.SS "void clear_buffer ()"

.PP
Function for clearing the input buffer\&. This function clears the input buffer before moving to the next line\&.
.br

.br
 Эта функция очищает буфер ввода до перехода на следующую строку\&. 
.SS "bool equal_double (double a, double b)"

.PP
Function for comparing 2 numbers of type double\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP the first double number 
.br
\fIb\fP the second double number
.RE
.PP
A constant is used for comparison, if the difference between the stored double values differs by less than this constant, these numbers are considered equal\&.
.br

.br
 Для сравнения используется константа, если разница между сохраннёными значениями double отличается меньше чем на эту константу, эти числа считаются равными\&.
.br
Если числа равны вернётся true иначе false\&.
.PP
\fBReturns\fP
.RS 4
true if the numbers are equal, otherwise false 
.RE
.PP

.SS "void fix_zero_double (double * a)"

.SS "void linear_equation (const \fBQE_coeff\fP coeff, \fBQE_roots\fP * roots)"

.PP
The function of solving a linear equation\&. 
.PP
\fBParameters\fP
.RS 4
\fIcoeff\fP coefficients of the quadratic equation
.br
\fIroots\fP roots of the linear equation
.RE
.PP
This function considers the linear case of a quadratic equation when the parameter a is 0, which is equivalent to a linear equation\&.
.br

.br
 Эта функция рассматривает часный случай квадратного уравнения, когда параметр a равен 0, что эквивалентно линейному уравнению\&. 
.SS "void quadratic_equation (const \fBQE_coeff\fP coeff, \fBQE_roots\fP * roots)"

.PP
The function of solving the correct quadratic equation\&. 
.PP
\fBParameters\fP
.RS 4
\fIcoeff\fP coefficients of the quadratic equation
.br
\fIroots\fP roots of the quadratic equation
.RE
.PP
This function considers the linear case of a quadratic equation when the parameter a is not equal to 0, which guarantees a non-infinite number of roots\&.
.br

.br
 Эта функция рассматривает часный случай квадратного уравнения, когда параметр a не равен 0, что гарантирует не бесконечное число корней\&. 
.SS "void solveqe (const \fBQE_coeff\fP coeff, \fBQE_roots\fP * roots)"

.PP
The function of solving the quadratic equation\&. 
.PP
\fBParameters\fP
.RS 4
\fIcoeff\fP coefficients of the quadratic equation
.br
\fIroots\fP roots of the quadratic equation
.RE
.PP
This function divides the quadratic equation into 2 cases\&.
.br
If a is 0, then the equation is treated as linear\&.
.br
If a is not equal to 0, then the equation is considered as a square equation that cannot have an infinite number of roots\&.
.br

.br
 Эта функция разделяет квадратное уравнение на 2 случая\&.
.br
Если a равен 0, то уравнение рассматривается как линейное\&.
.br
Если а не равен 0, то уравнение рассматривается как квадратное у которого не может возникнуть бесконечное колличество корней\&. 
.SS "void start_solve ()"

.PP
This function calls the user interface in the console\&. 
.SS "void swap_double (double * a, double * b)"

.PP
A function that swaps two numbers of the double type\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP pointer to a double number 
.br
\fIb\fP pointer to a double number
.br
\fIa\fP a double number 
.br
\fIb\fP a double number
.RE
.PP
This function swaps 2 double numbers\&.
.br

.br
 Эта функция меняет местами 2 числа типа double\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
