.TH "/mnt/c/Users/actim/code/c/square/unit_test.cpp" 3 "Fri Aug 26 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Users/actim/code/c/square/unit_test.cpp \- unit test code file  

.SH SYNOPSIS
.br
.PP
\fC#include 'quadratic_equation\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBread_test\fP (FILE *input_file, \fBQE_coeff\fP *coeff, \fBQE_roots\fP *roots)"
.br
.ti -1c
.RI "void \fBunit_test\fP ()"
.br
.RI "Function called for code testing\&. "
.ti -1c
.RI "void \fBoutput_answer\fP (\fBQE_roots\fP roots, const char *str)"
.br
.ti -1c
.RI "void \fBprint_tests_res\fP (int num_of_test, const \fBQE_coeff\fP coeff, const \fBQE_roots\fP corr_roots, int *count_false_test)"
.br
.RI "Function for checking the test with the output of information to the console\&. "
.ti -1c
.RI "bool \fBtestqe\fP (const \fBQE_coeff\fP coeff, const \fBQE_roots\fP corr_roots, \fBQE_roots\fP *test_roots)"
.br
.RI "A function that tests the operation of a test with certain parameters\&. "
.in -1c
.SH "Detailed Description"
.PP 
unit test code file 


.SH "Function Documentation"
.PP 
.SS "void output_answer (\fBQE_roots\fP roots, const char * str)"

.SS "void print_tests_res (int num_of_test, const \fBQE_coeff\fP coeff, const \fBQE_roots\fP corr_roots, int * count_false_test)"

.PP
Function for checking the test with the output of information to the console\&. 
.PP
\fBParameters\fP
.RS 4
\fInum_of_test\fP number of test 
.br
\fIcoeff\fP coefficients of the quadratic equation 
.br
\fIcorr_roots\fP correct roots of the quadratic equation
.br
\fIcount_false_test\fP invalid test counter
.RE
.PP
This function tests the program on certain data and outputs information to the console about whether the test was successfully passed and about the test\&.
.br

.br
 Эта функция тестирует программу на определённых данных и выводит в консоль информацию о том успешно ли пройден тест и о сомом тесте\&. 
.SS "bool read_test (FILE * input_file, \fBQE_coeff\fP * coeff, \fBQE_roots\fP * roots)"

.SS "bool testqe (const \fBQE_coeff\fP coeff, const \fBQE_roots\fP corr_roots, \fBQE_roots\fP * test_roots)"

.PP
A function that tests the operation of a test with certain parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fIcoeff\fP coefficients of the quadratic equation 
.br
\fIcorr_roots\fP correct roots of the quadratic equation
.br
\fItest_roots\fP the found roots of the quadratic equation
.RE
.PP
This function does not contain sets of tests, but only calls the main testing function on predefined input and output data\&.
.br

.br
 Эта функция не содержит набот тестов, а только вызывает функцию основного тестирования на заранее определённых входных и выходных данных\&.
.br
В случае если верный ответ совподает с выводом программы возврощается true иначе false\&.
.PP
\fBReturns\fP
.RS 4
If the correct answer coincides with the output of the program, true is returned otherwise false\&. 
.RE
.PP

.SS "void unit_test ()"

.PP
Function called for code testing\&. This function is called when you specify the start of the program -d \&.
.br
It contains a set of tests and checks the operation of the main program on them using the \fBtestqe()\fP function\&.
.br
Also, this function outputs information about the passed tests and the result of the check to the console\&.
.br

.br
 Данная функция вызывается при указании запуска программы -d \&.
.br
Она содержит набор тестов и проверяет на них работу основной программы с помощью функции \fBtestqe()\fP\&.
.br
Так же эта функция выводит в консоль информацию о пройденных тестах и результат проверки\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
