.TH "/mnt/c/Users/actim/code/c/square/unit_test.cpp" 3 "Wed Aug 24 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Users/actim/code/c/square/unit_test.cpp \- unit test code file  

.SH SYNOPSIS
.br
.PP
\fC#include 'quadratic_equation\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBunit_test\fP ()"
.br
.ti -1c
.RI "bool \fBtestqe\fP (double a, double b, double c, int *count_root, double *ans)"
.br
.in -1c
.SH "Detailed Description"
.PP 
unit test code file 


.SH "Function Documentation"
.PP 
.SS "bool testqe (double a, double b, double c, int * count_root, double * ans)"

.SS "void unit_test ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
