.TH "/mnt/c/Users/actim/code/c/square/unit_test.cpp" 3 "Thu Aug 25 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Users/actim/code/c/square/unit_test.cpp \- unit test code file  

.SH SYNOPSIS
.br
.PP
\fC#include 'quadratic_equation\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBunit_test\fP ()"
.br
.RI "Function called for code testing\&. "
.ti -1c
.RI "void \fBoutputs_with_test\fP (int num_of_test, double *test, int count_root, int *count_false_test)"
.br
.RI "функция для проверки теста с выводом информации в консиль "
.ti -1c
.RI "bool \fBtestqe\fP (double a, double b, double c, int *count_root, double *ans)"
.br
.RI "A function that tests the operation of a test with certain parameters\&. "
.in -1c
.SH "Detailed Description"
.PP 
unit test code file 


.SH "Function Documentation"
.PP 
.SS "void outputs_with_test (int num_of_test, double * test, int count_root, int * count_false_test)"

.PP
функция для проверки теста с выводом информации в консиль 
.PP
\fBParameters\fP
.RS 4
\fInum_of_test\fP number of test 
.br
\fItest\fP pointer to an array containing test data 
.br
\fIcount_root\fP the variable number of roots 
.br
\fIcount_false_test\fP pointer to the invalid test counter
.br
\fIcount_false_test\fP invalid test counter
.RE
.PP
This function tests the program on certain data and outputs information to the console about whether the test was successfully passed and about the test\&.
.br

.br
 Эта функция тестирует программу на определённых данных и выводит в консоль информацию о том успешно ли пройден тест и о сомом тесте\&. 
.SS "bool testqe (double a, double b, double c, int * count_root, double * ans)"

.PP
A function that tests the operation of a test with certain parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP parameter of the quadratic equation 
.br
\fIb\fP parameter of the quadratic equation 
.br
\fIc\fP parameter of the quadratic equation 
.br
\fIcount_root\fP pointer to the number of roots of the quadratic equation 
.br
\fIans\fP pointer to the array of roots of the equation
.RE
.PP
This function does not contain sets of tests, but only calls the main testing function on predefined input and output data\&.
.br

.br
 Эта функция не содержит набот тестов, а только вызывает функцию основного тестирования на заранее определённых входных и выходных данных\&.
.br
В случае если верный ответ совподает с выводом программы возврощается true иначе false\&.
.PP
\fBReturns\fP
.RS 4
If the correct answer coincides with the output of the program, true is returned otherwise false\&. 
.RE
.PP

.SS "void unit_test ()"

.PP
Function called for code testing\&. This function is called when the compilation flag is specified -D TEST \&.
.br
It contains a set of tests and checks the operation of the main program on them using the \fBtestqe()\fP function\&.
.br
Also, this function outputs information about the passed tests and the result of the check to the console\&.
.br

.br
 Данная функция вызывается при указании флага компиляции -D TEST \&.
.br
Она содержит набор тестов и проверяет на них работу основной программы с помощью функции \fBtestqe()\fP\&.
.br
Так же эта функция выводит в консоль информацию о пройденных тестах и результат проверки\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
